### ISSUE TITLE
Question about CAPE

### ISSUE THREAD

**Issue by saifullah3396** [NapierNLP/CAPE#2]
Hi, I wanted to ask whether we can use CAPE by adding noise on word level instead of adding noise after taking the mean embedding. Do you think this will have same privacy gaurantees?

**Comment by richplant** [comment]
Thanks for the question! Our noise implementation is scaled to the sensitivity of the embedding, hence why we constrain the range of the vector (see [Shokri et al. 2015](https://dl.acm.org/doi/10.1145/2810103.2813687) and [Maheshwari et al. 2022](https://arxiv.org/abs/2205.06135) for more on this). In order to apply this at the word level, you would need to decompose the sensitivity across  each dimension of each word - I'm not sure our approach would be appropriate here.
